### PR TITLE
Transmission#endpoint: don't concat everytime this method is called

### PR DESCRIPTION
**Pull request by benben**

### CODE REVIEW

**Comment by rajumsys** [comment]
@benben Thank a lot for this PR. It's a great catch. I didn't realize this until your PR :). However, can you please add unit test(s) for this change?

**Comment by rajumsys** [comment]
@benben I've already written the tests. I can push them to your branch if you add me to your rep. 

Thanks

**Comment by benben** [comment]
@rajumsys ooops, I saw your second comment just after I fixed it by myself.

I saw travis red locally and on travis because the newly released rake 11 makes problems. I bumped it to <11 in another commit. hope this is ok!

**Comment by benben** [comment]
@rajumsys I've added another test to be more aligned with your solution. :raising_hand: 

be aware that 2e8c9394c0e1bdf828313f17d611eb1a97a310ec is not included in my branch and you should cherry-pick it to master.

**Comment by rajumsys** [comment]
@benben Thanks. I'll merge this and add the missing comment in another PR.

**Pull request merged**
